from django.db import models

# Create your models here.
class V_Fac_ClientesB5(models.Model):
    C_Empresa= models.CharField(max_length=500)
    C_Tipo_Identi= models.CharField(max_length=500)
    C_Cod_Cliente= models.CharField(max_length=500)
    D_Nom_Cliente= models.CharField(max_length=500)
    D_Nom2_Cliente= models.CharField(max_length=500)
    D_Ape_Cliente= models.CharField(max_length=500)
    D_Ape2_Cliente= models.CharField(max_length=500)
    Cliente= models.CharField(max_length=500)
    Direccion_Clien= models.CharField(max_length=500)
    C_Ciudad= models.CharField(max_length=500)
    N_Ciudad= models.CharField(max_length=500)
    C_Region= models.CharField(max_length=500)
    N_Region= models.CharField(max_length=500)
    C_Pais= models.CharField(max_length=500)
    N_Pais_Es= models.CharField(max_length=500)
    Cod_Postal= models.CharField(max_length=500)
    N_Cod_Postal= models.CharField(max_length=500)
    N_Sector= models.CharField(max_length=500)
    Tel1= models.CharField(max_length=500)
    Tel2= models.CharField(max_length=500)
    Contacto_mail= models.CharField(max_length=500)
    Cod_Operador_tel1= models.CharField(max_length=500)
    Nom_Operador= models.CharField(max_length=500)
    F_Ingreso= models.CharField(max_length=500)
    Ult_Fec_Fac= models.CharField(max_length=500)
    C_Lider= models.CharField(max_length=500)
    Lider= models.CharField(max_length=500)
    C_Vendedor= models.CharField(max_length=500)
    Vendedor= models.CharField(max_length=500)
    C_Director= models.CharField(max_length=500)
    Director= models.CharField(max_length=500)
    C_Regional= models.CharField(max_length=500)
    Regional= models.CharField(max_length=500)
    Flag_Vigente= models.CharField(max_length=500)
    